# Generated by Django 5.2 on 2025-04-25 16:02

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("date", models.DateField(auto_now_add=True)),
                ("content", ckeditor.fields.RichTextField()),
                ("is_actual", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.AlterField(
            model_name="contact",
            name="company",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
