# Generated by Django 5.2 on 2025-04-25 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CachedAPIData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("api_name", models.CharField(max_length=50, unique=True)),
                ("data", models.JSONField()),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
